# Numpy

Importing Numpy

In [1]:
import numpy as np

Its a C API for connecting numpy with libraries written in C,C++,FORTRAN

In [2]:
data = np.array([[2,3,5,6],[6,7,8,9]])
data 

array([[2, 3, 5, 6],
       [6, 7, 8, 9]])

In [4]:
data.dtype

dtype('int64')

In [5]:
data*10

array([[20, 30, 50, 60],
       [60, 70, 80, 90]])

It'll not apply until we pass with variable name like assign it

In [6]:
data

array([[2, 3, 5, 6],
       [6, 7, 8, 9]])

In [7]:
data.shape

(2, 4)

In [9]:
data1 = [2,3,4,5,6,7]
print(type(data1))

<class 'list'>


In [10]:
arr1 = np.array(data1)
arr1.dtype

dtype('int64')

It can get multi dimensional list as well even with float

In [11]:
data2 = [[2.3,4.5,6.7],[0.5,5.6,0.9]]
print(type(data2))

<class 'list'>


In [15]:
arr2 = np.array(data2)
print(arr2)
arr2.dtype

[[2.3 4.5 6.7]
 [0.5 5.6 0.9]]


dtype('float64')

In [17]:
arr2.shape

(2, 3)

We can create zeroes array

In [18]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

or an empty array even with multi dimensions

In [20]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Empty doesnt mean its always zero, it intializes with garbage values

we can use arange to deploy numbers within a range

In [21]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Playing with data types

In [23]:
arr3 = np.array([1,2,3],dtype=np.float64)
arr3

array([1., 2., 3.])

In [24]:
arr3.dtype

dtype('float64')

Typecasting

In [26]:
arr4 = arr3.astype(np.int64)
arr4

array([1, 2, 3])

Now its again integer, also if we convert float to int, decimail part will be truncated only int will preserved

In [27]:
arr = np.array([3.01,3.99,3.5],dtype=np.float64)
arr

array([3.01, 3.99, 3.5 ])

In [30]:
arr_int = arr.astype(np.int64)
arr_int


array([3, 3, 3])

We can also extract numbers from strings

In [31]:
numeric_strings = np.array(["23.4","34","90"],dtype=np.str_)
numeric_strings

array(['23.4', '34', '90'], dtype='<U4')

In [35]:
arr = numeric_strings.astype(np.float64)
arr

array([23.4, 34. , 90. ])

We can rob data type from diffrent variables even if we dont know

In [36]:
which_variable = np.array([23,34,65,67],dtype=np.int32)
which_variable

array([23, 34, 65, 67], dtype=int32)

In [37]:
another_variable = np.array([23.34,0.76,43.45],dtype=np.float32)
another_variable

array([23.34,  0.76, 43.45], dtype=float32)

In [39]:
another_variable.astype(which_variable.dtype)

array([23,  0, 43], dtype=int32)

## *Vectorization*

its arihmatic with numpy arrays

In [40]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [43]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [44]:
arr1*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [45]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
arr2 = np.array([[11,22,33],[44,55,66]])
arr2

array([[11, 22, 33],
       [44, 55, 66]])

In [49]:
arr1*arr2

array([[ 11,  44,  99],
       [176, 275, 396]])

we casn make a boolean out of it

In [50]:
arr1%2==0

array([[False,  True, False],
       [ True, False,  True]])

In [51]:
arr2>arr1

array([[ True,  True,  True],
       [ True,  True,  True]])